site_name: JamesZOU的Web学习档案
site_description: JamesZOU的Web学习档案
site_author: JamesZOU的Web学习档案
repo_url: https://github.com/wowoo-technology/wowootech
copyright: Copyright © 2020 JamesZOU All Rights Reserved. JamesZOU 版权所有

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:

        - yaml

nav:
- 主页: index.md
- HTML: html/index.md
- CSS: css/index.md
- JavaScript: javascript/index.md
- JQuery: jquery/index.md
- Vue: vue/index.md